
GET http://localhost:8080/medicos HTTP/1.1

###

GET http://localhost:8080/medicos?size=4&page=0&sort=nome,desc HTTP/1.1

###

POST http://localhost:8080/medicos HTTP/1.1
content-type: application/json

{
    "nome": "Alvarenga Peixoto",
    "email": "alvarenga@gmail.com",
    "crm": "7853",
    "especialidade": "ANESTESIOLOGISTA",
    "endereco": {
        "logradouro": "Alvares Cabral",
        "bairro": "Anchieta",
        "cep": "65998708",
        "cidade": "Belo Horizonte",
        "uf": "MG",
        "complemento": "",
        "numero": ""
    }
}

###

POST http://localhost:8080/medicos HTTP/1.1
content-type: application/json

{
    "nome": "Mariana Silva",
    "email": "mariana.silva@example.com",
    "telefone": "3555659595",
    "crm": "1234",
    "especialidade": "GINECOLOGIA",
    "endereco": {
        "logradouro": "Rua das Flores",
        "bairro": "Centro",
        "cep": "12345678",
        "cidade": "São Paulo",
        "uf": "SP",
        "complemento": "Apto 501",
        "numero": "123"
    }
}

###

POST http://localhost:8080/medicos HTTP/1.1
content-type: application/json

{
    "nome": "Rafael Oliveira",
    "email": "rafael.oliv@example.com",
    "telefone": "355565239595",
    "crm": "1245",
    "especialidade": "CARDIOLOGIA",
    "endereco": {
        "logradouro": "Av. das Palmeiras",
        "bairro": "Jardins",
        "cep": "54321098",
        "cidade": "Rio de Janeiro",
        "uf": "RJ",
        "complemento": "",
        "numero": "567"
    }
}

###

POST http://localhost:8080/medicos HTTP/1.1
content-type: application/json

{
    "nome": "Juliana Santos",
    "email": "juliana.santos@example.com",
    "telefone": "3555659595",
    "crm": "2468",
    "especialidade": "DERMATOLOGIA",
    "endereco": {
        "logradouro": "Rua dos Lírios",
        "bairro": "Floresta",
        "cep": "98765432",
        "cidade": "Porto Alegre",
        "uf": "RS",
        "complemento": "",
        "numero": "987"
    }
}

###

PUT http://localhost:8080/medicos HTTP/1.1
content-type: application/json

{
    "id": 3,
    "nome": "Rafael Silva",
    "telefone": "3198989898"
}

###

DELETE  http://localhost:8080/medicos/2 HTTP/1.1